### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by Severin-Ek** [ds4owd-001/md-02-assignments-Severin-Ek#1]
Hello @larnsce @mianzg @sskorik01.
I now inform you that I have successfully completed the assignment of module 2.
Thanks for your support.

**Comment by Severin-Ek** [comment]
The only concern I have is related to the task 6.

`3-Do not display (ignore) the outliers in the plot. Note: Use a search engine or an AI tool to find the solution and add the link to the solution you have found.`
I did not face any challenges here. However, I think that I don't get what is meant there. Thanks

**Comment by sskorik01** [comment]
Hi, congratulations for completing the exercise. I can see that you haven't committed your code to GitHub (the code in your md-02a-data-visualization.qmd file has not been updated), could you please do that? 

Concerning your question related to task 6, did you manage to not display the outliers? If so how did you do it? The idea here was for you to search the right function on your own (via Google, ChatGPT, Perplexity.ai or another tool).

**Comment by Severin-Ek** [comment]
@sskorik01 
Thanks for your feedback. 
You are right. I did not "Push" after I committed. I just checked and did it. Can you please check out and let me know if it is okay? Thanks in advance.
